{% set name = "repoze.lru" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "0429a75e19380e4ed50c0694e26ac8819b4ea7851ee1fc7583c8572db80aff77"

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - repoze
    - repoze.lru
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://www.repoze.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: A tiny LRU cache implementation and decorator
  description: |
    The Repoze project is a collection of technologies which bridges the WSGI
    and Zope worlds.
  doc_url: https://repoze.readthedocs.io/
  dev_url: https://github.com/repoze/

extra:
  recipe-maintainers:
    - nehaljwani
  skip-lints:
    - http_url
